server.port=8080
server.address=0.0.0.0
spring.datasource.url=jdbc:mysql://db-torneo:3306/torneo_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
